version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  android: circleci/android@2.5.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    # These next lines define the Android machine image executor.
    # See: https://circleci.com/docs/2.0/executor-types/
    executor:
      name: android/android-machine
      tag: default
      resource-class: large

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - run: ls -l /opt/android/sdk/build-tools

      - android/change-java-version:
          java-version: 17
    
      # Checkout the code as the first step.
      - checkout
      - run: echo "Git checkout complete"

      - run: git submodule sync
      - run: git submodule update --init --recursive --jobs 8
      - run: echo "Git submodule update complete"
      - run: sh 'chmod +x gradlew'
      

      # And finally run the release build
      - run:
          name: Assemble release build
          no_output_timeout: 30m
          command: |
            ./gradlew assemblePrcRelease   --stacktrace

      - store_artifacts:
          path: android/out/app/outputs/apk

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  app-release: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test